Add a lint check for generated code

diff --git a/script/lint b/script/lint
--- a/script/lint
+++ b/script/lint
@@ -2,7 +2,18 @@
 
 set -eu
 
+: "${GITHUB_ACTIONS:=}"
+
 cd "$(dirname "$0")"
 cd ..
 
-exec go run github.com/golangci/golangci-lint/cmd/golangci-lint run
+go generate ./...
+if ! git diff --exit-code >/dev/null; then
+  echo "Error: generated code is not up-to-date! Run 'go generate ./...' and update your branch." >&2
+  exit 1
+fi
+
+# On GitHub actions, this is run as a separate task
+if [ "$GITHUB_ACTIONS" != "true" ]; then
+  exec go run github.com/golangci/golangci-lint/cmd/golangci-lint run
+fi
